== Wat?
* Dependencies van een object laten voorzien door een ander object.
* Dependencies worden centraal beheerd in een container.

== Waarom?
* Je wilt je implementatie laten variëren al naargelang de context van de applicatie.
* Maakt code minder dependent van elkaar.
* Voorbeeld: Je hebt drie lagen: een datalaag (een mysql database), een businesslaag (logica) en je viewlogica. Als je je datalaag laat afhangen van de dependency injection ben je niet gebonden aan één implementatie en kan je bv heel simpel de mysql vervangen door een REST implementatie.

== Hoe?
* Zit standaard ingebouwd in ASP.NET MVC
* Interfaces via constructor injection resolven.

Concrete stappen:

1. Definieer je interface.
2. Definieer je implementatie(s).
3. Voeg je dependency toe aan de container door in de `ConfigureServices` van je `Startup.cs` `services.AddTransient<IMyService, MyService>();` toe te voegen.
4. Roep de dependency toe aan de benodigde classes via constructor injection. Wanneer je je code gaat runnen gaat de container automatisch een juist object injecteren in de runtime waar nodig.
[source,csharp]
----
private IMyService _myService;

public APIController(IMyService myService)
{
    _myService = myService;
}
----

== Lifecycle

|===
|Scope|Beschrijving|Voorbeeld

|Transient|Eén instantie per container request|IHttpContextFactory
|Scoped|Eén instantie per web-service request|EntityContext (EntityFramework)
|Singleton|één instantie voor héél de applicatie.|ILoggerFactory
|===
